### ISSUE TITLE
Cannot find module 'tslib'

### ISSUE THREAD

**Issue by selimyoussry** [heroku/heroku-cli-deploy#13]
Hi there,

On a fresh install of heroku-cli on:
- Ubuntu 18.04
- node 10.2

When running
- `sudo apt install heroku`
- `heroku plugins:install heroku-cli-deploy`

When I run `heroku deploy:jar` or even just `heroku` I get the error 
```
(node:5887) [MODULE_NOT_FOUND] @oclif/plugin-legacy: Plugin heroku-cli-deploy: Error: Cannot find module 'tslib'
/home/selim/.local/share/heroku/node_modules/heroku-cli-deploy
```

My deployments don't work anymore. I tried replicating that in a fresh Debian container and get the same error. Is there an issue with the latest heroku-cli-deploy?

To reproduce, put this minimal setup in a Dockerfile:
```
FROM node:9

RUN npm install -g heroku
RUN heroku plugins:install heroku-cli-deploy

ENTRYPOINT ["/usr/local/bin/heroku"]
```
then run `docker build -t minimalherokucli .` (might need `sudo`)
and `docker run minimalherokucli` (might need `sudo`)

and you'll get the error
```
(node:1) [MODULE_NOT_FOUND] @oclif/plugin-legacy: Plugin heroku-cli-deploy: Error: Cannot find module 'tslib'
/root/.local/share/heroku/node_modules/heroku-cli-deploy
CLI to interact with Heroku
```

Any help is appreciated,
Thank you

**Comment by jkutner** [comment]
@selimyoussry if you try this again after running `heroku update` I think it should work. Can you confirm this for me? Thanks.

**Comment by selimyoussry** [comment]
@jkutner Looks like it's fixed now, thanks!
