### ISSUE TITLE
How do you set env variables like spring.profiles.active?

### ISSUE THREAD

**Issue by magbicaleman** [heroku/heroku-cli-deploy#17]
For the life of me, I can't figure this out :).

**Comment by magbicaleman** [comment]
Not resolved, but also not a good issue.

**Comment by jkutner** [comment]
@magbicaleman Environment variable names with `.` chars are not allowed by Bash, Spring, and other tools/frameworks. I think you want to name your config var like:

```
$ heroku config:set SPRING_PROFILES_ACTIVE="foobar"
```

For more info, see the Spring docs on [External Configuration](https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html).

Alternatively, you can provide `-Dspring.profiles.active=foobar` in `JAVA_OPTS` or `--spring.profiles.active=foobar` in `JAR_OPTS` (depending on how you're deploying).
