### ISSUE TITLE
heroku deploy:jar does not delete /tmp/heroku-deploy files

### ISSUE THREAD

**Issue by ckaiser79** [heroku/heroku-cli-deploy#18]
When invoking 
```
heroku deploy:jar my-application.jar --app my-application
```

A temporary directory is created:
![grafik](https://user-images.githubusercontent.com/11504021/63871132-93f6c080-c9bb-11e9-98bb-621f06c534e7.png)

After a successfull run this directory is not deleted. I would expect heroku to delete its created temp directories on success and on failure.

```
heroku --version
heroku/7.29.0 linux-x64 node-v11.14.0
```
Plugins have been updated before testing.

**Comment by jkutner** [comment]
I think the relevant code is here: https://github.com/heroku/heroku-maven-plugin/blob/ad3ed9d66a1b1c7269ed5be465c09b7f41f356e9/heroku-deploy/src/main/java/com/heroku/sdk/deploy/App.java#L69

**Comment by ckaiser79** [comment]
Thanks Joe, I tried a pull request to fix it: https://github.com/heroku/heroku-maven-plugin/pull/48

**Comment by jkutner** [comment]
@ckaiser79 this should be fixed in [@heroku-cli/plugin-java](https://www.npmjs.com/package/@heroku-cli/plugin-java) 3.0.4 (this repo is actually deprecated, and merged into [plugin-java](https://github.com/heroku/plugin-java))
