### ISSUE TITLE
 I could not pass Procfile with jar to Heroku's free dyno.

### ISSUE THREAD

**Issue by mielecmichal** [heroku/heroku-cli-deploy#2]
I run following commands from directory containing both .jar and Procfile:

```
heroku create appName --no-remote
heroku deploy:jar appName.jar  --app appName
```

but `heroku ps --app appName` shows default run command all the time:
`java $JAVA_OPTS -jar appName.jar  $JAR_OPTS`

`heroku deploy:jar appName.jar  --app appName -i Procfile`
and
`heroku deploy:jar --jar appName.jar  --app appName -i Procfile`
 also doesn't work.

My Procfile is: `web java -jar appName.jar --server.port=$PORT` and application is Spring Boot based.

Installed version:

```
heroku-cli-deploy@0.1.2
```

**Comment by machowski** [comment]
have you managed to solve this issue? I'm having same problem, no matter what I do, Procfile gets ignored.

**Comment by jkutner** [comment]
@mielecmichal Make sure your `Procfile` has `web:` at the front (not `web` without the colon).

@machowski can you try the same thing? If you have a different cause can you elaborate.

**Comment by spazbob** [comment]
I was also experiencing something similar and raised a support ticket with Heroku. I then did some digging myself and found that this plugin uses the Java-based Heroku Maven plugin under the hood. Checking the code of the Maven plugin showed that it was always hardcoding a web dyno in the Procfile, **then** including whatever Procfile you had uploaded.

It looks like they've fixed this in the last five minutes here in response to my ticket - https://github.com/heroku/heroku-maven-plugin/commit/3a6fc452a501891bfdbe3ce9be49a70aaaca49b3 - so might be worth trying again in a few days (not sure how frequently the plugins are built)

**Comment by jkutner** [comment]
I'm closing this. We can reopen in more info is provided.

**Comment by magbicaleman** [comment]
I'm having the issue with `-i Procfile` where my Profile has the following;

`web: java $JAVA_OPTS -Dspring.profiles.active=MY_ENV -jar target/dependency/webapp-runner.jar  --port $PORT --expand-war target/*.war`

but then heroku just keeps out putting

`web: java $JAVA_OPTS -jar webapp-runner.jar ${WEBAPP_RUNNER_OPTS} --port $PORT ./target/NAME.war`

It's completely ignoring what's in my Procfile or at least it seems that way.

**Comment by jkutner** [comment]
@magbicaleman the `heroku deploy:war` command doesn't support a custom `Procfile`. Instead, you can either set those config vars (`JAVA_OPTS`, `WEBAPP_RUNNER_OPTS`, etc) to customize the options or you can switch to `heroku deploy:jar`.

**Comment by magbicaleman** [comment]
I just sent you an email crying for help. 

> Instead, you can either set those config vars (JAVA_OPTS, WEBAPP_RUNNER_OPTS, etc) 

I would then go to config vars in heroku, and add WEBAPP_RUNNER_OPTS or JAVA_OPTS and put `--spring.profiles.active=NAME` ?

**Comment by jkutner** [comment]
hmm, for `war:run` you might need some other way to define the profile. I recommend having a default in your `application.yml` so that you don't need to specify anything locally.
