### ISSUE TITLE
Slugs have commit value of "null"

### ISSUE THREAD

**Issue by rwz** [heroku/heroku-cli-deploy#4]
Slugs created using `heroku deploy:jar` command have commit value of `"null"` string.

Example release: 237a85c0-df18-4eaf-9523-768561ace491

**Comment by jkutner** [comment]
Fixed by:

* https://github.com/heroku/heroku-maven-plugin/commit/d89607063cde97be3327580448d8bcf35d7dfc36
*  https://github.com/heroku/heroku-cli-deploy/commit/b444cc18b6fdd0d0265c1b67bfbc8928c2307d8f
