### ISSUE TITLE
Cannot get rest end points when i deploy with this

### ISSUE THREAD

**Issue by chanakaDe** [heroku/heroku-cli-deploy#6]
http://serene-headland-77553.herokuapp.com
This is the link of my deployed application.

then i tried to access my rest end points.
The system is working fine locally.
the local url is as follows.

http://localhost:8080/api/elastic-test/master/track/search_advanced?text=Genes&species=homo_sapiens&type=gene&release=89&division=ensembl

so i replaced the host and port with Heroku host. Like this :

http://serene-headland-77553.herokuapp.com/api/elastic-test/master/track/search_advanced?text=Genes&species=homo_sapiens&type=gene&release=89&division=ensembl

But it always give me 404. I tried these days figuring out what' s the issue. Still no good. Do you have any understanding on this ? any idea ?

**Comment by chanakaDe** [comment]
@jkutner Can you please help me 👍

**Comment by jkutner** [comment]
@chanakaDe i'm not sure what would cause that. Can you open a ticket at https://help.heroku.com
