### ISSUE TITLE
Parameter build-version usage is unclear.

### ISSUE THREAD

**Issue by jannylund** [heroku/heroku-cli-deploy#8]
Hey.

The parameter --build-version seem to be filtered on the heroku side. The plugin gives no explanation on how to use it or what is supported, and neither does the documentation.

For example, the following works:
```
heroku deploy:jar webapp.jar --app webapp --build-version `git rev-parse --short HEAD`
```

But the following does not work, not leave any error, nor explanation.

```
heroku deploy:jar webapp.jar --app webapp --build-version v1.0.0
```

Suggestion: If you can find the internal documentation, maybe we could document this properly to avoid confusion?

Related stackoverflow: https://stackoverflow.com/questions/41284667/heroku-cli-deploy-how-to-specify-the-version

**Comment by jkutner** [comment]
It looks like the bug is actually in the Dashboard, which displays the values. If you check with the CLI by running `heroku releases`, you should see the version you passed in.

I've opened an internal issue to get the Dashboard fixed. I'll update this one when it's resolved.

**Comment by jannylund** [comment]
That's actually great. My original intention was to push the proper version tag generated by `git describe --tags`. Hopefully this solves the case!

**Comment by jannylund** [comment]
@jkutner I can confirm that this is working in heroku portal now! :)
