### ISSUE TITLE
buildpacks option for JVM metrics doesn't appear to work

### ISSUE THREAD

**Issue by spazbob** [heroku/heroku-cli-deploy#9]
I have tried following the instructions at https://devcenter.heroku.com/articles/language-runtime-metrics#pre-compiled-configuration to enable JVM metrics whilst using the Heroku Deploy CLI plugin.

I have the following command in a Windows Batch file (running on Windows 10):

`heroku deploy:war --war target\myapp.war --app myapp --webapp-runner 8.5.23.0 --buildpacks "heroku/metrics|heroku/jvm"`

However, on executing this I always get the same error:

>  !    /jvm is not a heroku command.
>  !    Perhaps you meant java:visualvm
>  !    Run heroku help for a list of available topics.

I've tried removing the double quotes, and also tried replacing them with single quotes, with no change. This command works fine without the --buildpacks option.

Running heroku update and heroku plugins gives me the following output:

> heroku-cli: Updating CLI... already on latest version: 6.14.36-15f8a25
> heroku-cli: Updating plugins... done

> heroku-cli-deploy 0.3.1
> heroku-cli-java 2.2.1

**Comment by spazbob** [comment]
When I remove the `|heroku/jvm`, the command runs successfully and uploads my app, but it doesn't have the heroku/jvm buildpack so can't run java. Seems like maybe the pipe character may be causing the problem?

**Comment by jkutner** [comment]
Ah interesting. I need to test this on Windows, but I think the problem might be the underlying `java` command used to deploy the app. I should have a fix for this soon.

**Comment by jkutner** [comment]
@spazbob I'm changing the delimiter from a `|` to a `,`, which seems to work better on all platforms. I should have this released today.

**Comment by jkutner** [comment]
https://github.com/heroku/heroku-maven-plugin/commit/b95b86371251f16fb317ba70b1ed45c924738f8a

**Comment by spazbob** [comment]
Now working for me in heroku-cli-deploy 0.3.2. Thanks Joe!

**Comment by spazbob** [comment]
Spoke to soon. Heroku-cli-deploy is now picking up the buildpack, but it's not installing the agent for some reason so the app then fails.

Build log on my app that uses the maven plugin:

-----> HerokuRuntimeMetrics app detected
-----> Setting up .profile.d to automatically run agentmon...
-----> Installing Java metrics agent
-----> heroku-maven-plugin app detected
-----> Installing OpenJDK 1.8... done

Build log on my app that uses heroku-cli-deploy:

-----> HerokuRuntimeMetrics app detected
-----> Setting up .profile.d to automatically run agentmon...
-----> heroku-deploy app detected
-----> Installing OpenJDK 1.8... done

The "Installing Java metrics agent" line is missing, and the app then fails because the Procfile references the agent, but it's not there:

Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -Dfile.encoding=UTF-8 -javaagent:bin/heroku-metrics-agent.jar  
Error opening zip file or JAR manifest missing : bin/heroku-metrics-agent.jar

**Comment by jkutner** [comment]
@spazbob Can you try the following command:

```
heroku deploy:war --war target\myapp.war --app myapp --webapp-runner 8.5.23.0 --buildpacks "https://github.com/heroku/heroku-buildpack-metrics.git#jkutner/abs-path,heroku/jvm"
```

The jkutner/abs-path branch on the metrics buildpack has a fix that I think might be the cause.

**Comment by spazbob** [comment]
Still not working - now the error message has just changed to:

Error opening zip file or JAR manifest missing : /app/bin/heroku-metrics-agent.jar

instead of 

Error opening zip file or JAR manifest missing : bin/heroku-metrics-agent.jar

**Comment by spazbob** [comment]
I just logged into my instance via the Run console from dashboard (not Heroku exec) and I don't see any bin directory in /app (though not sure if Run console applies the buildpack?)

**Comment by spazbob** [comment]
Tried connecting to the dyno vis heroku ps:exec but I can't connect as the dyno is constantly crashing due to the missing agentlib

**Comment by jkutner** [comment]
@spazbob i think I know what the problem is. Try reversing the buildpack order:

```
heroku deploy:war --war target\myapp.war --app myapp --webapp-runner 8.5.23.0 --buildpacks "heroku/jvm,heroku/metrics"
```

**Comment by spazbob** [comment]
Fixed! Did you just update the runtime metrics [here](https://devcenter.heroku.com/articles/language-runtime-metrics#pre-compiled-configuration) to change to be that round - I could swear I copied the command from there?! Then again, too much coffee not enough sleep :-)

Does the order of the buildpacks mean anything - in the Maven plugin the docs have the metrics one first, which is working fine.

**Comment by jkutner** [comment]
@spazbob yes, i changed it once I realize the problem :)

**Comment by jkutner** [comment]
@spazbob when running with Maven, the order doesn't matter because it copies the `pom.xml` into the slug and the buildpack detects the app as a Maven app. But when deploying with the heroku-cli-deploy, there is nothing but the WAR, and it doesn't detect anything. You can see the code here:
https://github.com/heroku/heroku-cli-deploy/issues/9#issuecomment-338789570

I'll be improving that to detect either WARs or webapp-runner.jar

**Comment by spazbob** [comment]
Makes sense now. Thanks for the help getting this fixed.

On the Heroku Support ticket, I raised a number of areas in the documentation that confused me previously - e.g. the use of heroku/jvm in the CLI example but jvm-common in the Maven plugin example - for others in future some tidy ups around that may be useful. Now that I've found the source for heroku-cli-deploy, heroku-maven-plugin and the various buildpacks I can dig into it, but in the ideal world you don't need to.

**Comment by jkutner** [comment]
@spazbob you're totally right. I'm really sorry you had to do so much work to get this sorted out. I've passed along all of your feedback to our product and documentation teams, and I've even changed some of the docs myself.

Thanks for your patience with us!

**Comment by spazbob** [comment]
No problem at all - glad to be able to contribute to the platform in a very small way.
